import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { quotesApi } from '../../api/quotes'
import Button from '../../components/UI/Button'
import Badge from '../../components/UI/Badge'
import EmptyState from '../../components/UI/EmptyState'
import { formatMoney } from '../../utils/money'
import { formatDate, formatDateTime } from '../../utils/dates'
import { professionLabel } from '../../utils/constants'

export default function QuoteDetail() {
  const { id } = useParams(); const navigate = useNavigate()
  const [quote, setQuote] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  async function load() { try { const data = await quotesApi.get(id); setQuote(data.quote) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [id])
  async function action(fn) { try { await fn(id); await load() } catch (err) { alert(err.message) } }
  if (loading) return <p className="text-sm text-gray-500">A carregar...</p>
  if (error) return <EmptyState title="Erro ao carregar orçamento" description={error} />
  if (!quote) return null
  const zones = quote.zones?.length ? quote.zones : [{ id: 'sem-zona', name: 'Itens sem zona' }]
  return <div className="mx-auto max-w-6xl space-y-5 print-page"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start print:hidden"><div><h2 className="text-2xl font-extrabold text-gray-900">Orçamento {quote.quote_number}</h2><p className="text-sm text-gray-500">{quote.client_name} · {professionLabel(quote.profession)}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => window.print()}>Imprimir / PDF</Button><Button variant="secondary" onClick={() => action(quotesApi.send)}>Enviar</Button><Button variant="secondary" onClick={() => action(quotesApi.approve)}>Aprovar</Button><Button variant="secondary" onClick={() => action(quotesApi.duplicate)}>Duplicar</Button><Button variant="danger" onClick={() => action(quotesApi.cancel)}>Anular</Button></div></div>
    <section className="rounded-2xl border bg-white p-6 shadow-sm print:shadow-none"><div className="flex flex-col justify-between gap-4 border-b pb-5 sm:flex-row"><div><h1 className="text-3xl font-extrabold text-gray-900">BuildQuote Pro</h1><p className="text-sm text-gray-500">Orçamento profissional para construção civil</p></div><div className="text-left sm:text-right"><Badge status={quote.status} /><p className="mt-2 text-sm text-gray-500">Criado em {formatDate(quote.created_at)}</p><p className="text-sm text-gray-500">Válido até {formatDate(quote.valid_until)}</p></div></div><div className="grid gap-4 py-5 md:grid-cols-2"><div><h3 className="font-bold text-gray-900">Cliente</h3><p>{quote.client_name}</p><p className="text-sm text-gray-500">{quote.client_email}</p><p className="text-sm text-gray-500">{quote.client_phone}</p><p className="text-sm text-gray-500">NIF: {quote.client_nif || '—'}</p><p className="text-sm text-gray-500">{quote.client_address}</p></div><div><h3 className="font-bold text-gray-900">Dados gerais</h3><p className="text-sm text-gray-500">Profissão: {professionLabel(quote.profession)}</p><p className="text-sm text-gray-500">Notas: {quote.notes || '—'}</p></div></div>{zones.map((zone) => { const items = quote.items?.filter((item) => item.zone_id === zone.id || zone.id === 'sem-zona') || []; return <div key={zone.id} className="mb-6"><h3 className="mb-2 text-lg font-bold text-gray-900">{zone.name}</h3><div className="overflow-x-auto rounded-xl border"><table className="min-w-full divide-y text-sm"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left">Descrição</th><th className="px-4 py-3 text-right">Qtd</th><th className="px-4 py-3 text-right">Preço</th><th className="px-4 py-3 text-right">IVA</th><th className="px-4 py-3 text-right">Total</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-4 py-3">{item.description}</td><td className="px-4 py-3 text-right">{item.quantity} {item.unit}</td><td className="px-4 py-3 text-right">{formatMoney(item.unit_price)}</td><td className="px-4 py-3 text-right">{item.vat_rate}%</td><td className="px-4 py-3 text-right font-bold">{formatMoney(item.total)}</td></tr>)}</tbody></table></div></div> })}<div className="ml-auto max-w-md rounded-2xl bg-blue-50 p-5"><div className="flex justify-between"><span>Subtotal</span><strong>{formatMoney(quote.subtotal)}</strong></div><div className="flex justify-between"><span>IVA</span><strong>{formatMoney(quote.vat_total)}</strong></div><div className="flex justify-between"><span>Desconto</span><strong>{formatMoney(quote.discount)}</strong></div><div className="mt-3 flex justify-between border-t pt-3 text-xl"><span className="font-bold">Total</span><strong className="text-blue-700">{formatMoney(quote.total)}</strong></div></div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm print:hidden"><h3 className="font-bold text-gray-900">Histórico de estados</h3><div className="mt-3 space-y-2">{quote.status_history?.map((item) => <div key={item.id} className="rounded-lg bg-gray-50 p-3 text-sm"><Badge status={item.new_status} /> <span className="ml-2 text-gray-500">{formatDateTime(item.created_at)} — {item.notes}</span></div>)}</div></section><Button variant="secondary" onClick={() => navigate('/quotes')} className="print:hidden">Voltar</Button></div>
}
