import { useEffect, useState } from 'react'
import Button from '../components/UI/Button'
import Input from '../components/UI/Input'
import Select from '../components/UI/Select'
import { professionsApi } from '../api/professions'
import { PROFESSIONS } from '../utils/constants'

export default function Settings() {
  const [form, setForm] = useState({ business_name: '', nif: '', profession: '', phone: '', email: '', address: '', service_area: '', logo_url: '', default_margin: 15 })
  const [modules, setModules] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { professionsApi.getProfessional().then((data) => { setForm({ ...form, ...(data.professional || {}) }); setModules(data.modules || []) }).catch((err) => setError(err.message)) }, [])
  async function save(event) { event.preventDefault(); setMessage(''); setError(''); try { const data = await professionsApi.updateProfessional(form); setForm({ ...form, ...data.professional }); setMessage('Configurações guardadas com sucesso.') } catch (err) { setError(err.message) } }
  return <div className="space-y-5"><div><h2 className="text-2xl font-extrabold text-gray-900">Configurações</h2><p className="text-sm text-gray-500">Dados do profissional/empresa e margens padrão.</p></div><form onSubmit={save} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Input label="Nome da empresa/profissional" value={form.business_name || ''} onChange={(e) => setForm({ ...form, business_name: e.target.value })} /><Input label="NIF" value={form.nif || ''} onChange={(e) => setForm({ ...form, nif: e.target.value })} /><Select label="Profissão" value={form.profession || ''} options={PROFESSIONS} onChange={(e) => setForm({ ...form, profession: e.target.value })} /><Input label="Telefone" value={form.phone || ''} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Input label="Email" type="email" value={form.email || ''} onChange={(e) => setForm({ ...form, email: e.target.value })} /><Input label="Zona de serviço" value={form.service_area || ''} onChange={(e) => setForm({ ...form, service_area: e.target.value })} /><Input label="Morada" value={form.address || ''} onChange={(e) => setForm({ ...form, address: e.target.value })} /><Input label="URL do logótipo" value={form.logo_url || ''} onChange={(e) => setForm({ ...form, logo_url: e.target.value })} /><Input label="Margem padrão (%)" type="number" value={form.default_margin || 15} onChange={(e) => setForm({ ...form, default_margin: Number(e.target.value) })} /></div>{message && <p className="mt-4 rounded-lg bg-green-50 p-3 text-sm text-green-700">{message}</p>}{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5"><Button type="submit">Guardar alterações</Button></div></form><section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold text-gray-900">Módulos ativos</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{modules.map((mod) => <div key={mod.module_code} className="rounded-xl border bg-gray-50 p-3"><p className="font-semibold text-gray-900">{mod.module_code}</p><p className="text-sm text-gray-500">{mod.is_enabled ? 'Ativo' : 'Inativo'}</p></div>)}</div></section></div>
}
